.\" Copyright 2020 Justin Hu
.\"
.\" SPDX-License-Identifier: LGPL-3.0-or-later

.TH DTHREADD 1 "October 2020" "0.1.0" "User Commands"
.SH NAME
dthreadd \- run a dthread server
.SH SYNOPSIS
.B dthreadd

.SH DESCRIPTION
.PP
Start a dthreadd server. The server asks for for a password, number of threads
per client, and port to bind to over stdout and stdin. Command line arguments
are ignored.

.SH AUTHOR
Written by Justin Hu.

.SH REPORTING BUGS
Bug reports at <https://github.com/JustinHuPrime/dthreads/issues>.

.SH COPYRIGHT
Copyright \(co 2020 Justin Hu.
License LGPLv3+: GNU Lesser GPL version 3 or later
<https://gnu.org/licenses/lgpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

.SH SEE ALSO
.BR dthread (3)